```yaml
name: Rclone Mount
version: 1.0
slug: rclone_mount
description: Mount Alist WebDAV using rclone for Home Assistant
arch:
  - aarch64
  - amd64
  - armv7
  - i386
image: rclone/rclone
init: false
host_network: true
options:
  remote: alist
  path: /
  mount_point: /mnt/webdav
schema:
  remote: str
  path: str
  mount_point: str
mounts:
  - name: config
    description: rclone config
    type: bind
    host_path: /share/rclone
    container_path: /config
  - name: webdav
    description: WebDAV mount point
    type: bind
    host_path: /share/webdav
    container_path: /mnt/webdav
cmd: ["mount", "{remote}:{path}", "{mount_point}", "--config", "/config/rclone.conf", "--allow-other", "--vfs-cache-mode", "writes"]
```