name: AList WebDAV Serve
version: 1.0.9
slug: alist_webdav_serve
description: Serves an AList WebDAV share over HTTP using rclone
url: https://github.com/your-repo/alist-webdav-serve
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  webdav_url: "http://192.168.0.142:5244/dav/OneDriveShare"
  username: ""
  password: ""
  serve_port: "8080"
schema:
  webdav_url: str
  username: str
  password: password
  serve_port: str
map:
  - data:rw
host_network: true
ports:
  8080/tcp: 8080
cap_add:
  - SYS_ADMIN
  - DAC_OVERRIDE