name: AList WebDAV Mount
version: 1.0.2
slug: alist_webdav_mount
description: Mounts an AList WebDAV share to a local directory using davfs2
url: https://github.com/your-repo/alist-webdav-mount
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  webdav_url: "http://192.168.0.142:5244/dav"
  username: ""
  password: ""
  mount_point: "/data/mount"
schema:
  webdav_url: str
  username: str
  password: password
  mount_point: str
map:
  - data:rw
devices:
  - /dev/fuse:/dev/fuse:rwm
cap_add:
  - SYS_ADMIN
host_network: true