name: AList WebDAV Mount
version: 1.0.6
slug: alist_webdav_mount
description: Mounts an AList WebDAV share as a virtual filesystem using rclone
url: https://github.com/your-repo/alist-webdav-mount
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  webdav_url: "http://192.168.0.142:5244/dav/OneDriveShare"
  username: ""
  password: ""
  mount_point: "/data/mount"
schema:
  webdav_url: str
  username: str
  password: password
  mount_point: str
map:
  - data:rw
host_network: true