name: AList STRM Serve
version: 1.0.11
slug: alist_strm_serve
description: Generates .strm files from AList WebDAV .mp4 files and serves them over HTTP using rclone
url: https://github.com/your-repo/alist-strm-serve
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  webdav_url: "http://192.168.0.142:5244/dav/OneDriveShare"
  username: ""
  password: ""
  alist_api_url: "http://192.168.0.142:5244/api"
  alist_token: ""
  serve_port: "8080"
schema:
  webdav_url: str
  username: str
  password: password
  alist_api_url: str
  alist_token: str
  serve_port: str
map:
  - data:rw
host_network: true
ports:
  8080/tcp: 8080
cap_add:
  - SYS_ADMIN
  - DAC_OVERRIDE