name: AList WebDAV Sync
version: 1.0.4
slug: alist_webdav_sync
description: Syncs an AList WebDAV share to a local directory using rclone
url: https://github.com/your-repo/alist-webdav-sync
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  webdav_url: "http://192.168.0.142:5244/dav"
  username: ""
  password: ""
  mount_point: "/data/mount"
schema:
  webdav_url: str
  username: str
  password: password
  mount_point: str
map:
  - data:rw
host_network: true