name: Rclone WebDAV Server
version: "1.0.0"
slug: rclone_webdav_server
description: Serve a WebDAV remote as a local WebDAV server using Rclone
url: https://github.com/yourusername/hassio-rclone-webdav-mount
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
init: false
map:
  - share:rw
  - config:rw
options:
  webdav_url: ""
  webdav_user: ""
  webdav_pass: ""
  mount_point: "/share/webdav_mount"
  vendor: "other"
schema:
  webdav_url: str
  webdav_user: str
  webdav_pass: password
  mount_point: str
  vendor: list(other|nextcloud|owncloud|sharepoint|fastmail)?
host_network: true
ports:
  "8080/tcp": 8080