name: Rclone WebDAV Mount
version: "1.0.0"
slug: rclone_webdav_mount
description: Mount a WebDAV remote to a local directory using Rclone
url: https://github.com/yourusername/hassio-rclone-webdav-mount
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
init: false
map:
  - share:rw
  - config:rw
options:
  webdav_url: ""
  webdav_user: ""
  webdav_pass: ""
  mount_point: "/share/webdav_mount"
  vendor: "other"
schema:
  webdav_url: str
  webdav_user: str
  webdav_pass: password
  mount_point: str
  vendor: list(other|nextcloud|owncloud|sharepoint|fastmail)?
host_network: false
privileged:
  - SYS_ADMIN
devices:
  - /dev/fuse